name: metrics.api.steam

on:
    schedule: [{ cron: "0 16 * * *" }]
    workflow_dispatch:

jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Steam profile
              uses: lowlighter/metrics@latest
              with:
                  filename: assets/metrics.plugin.steam.player.svg
                  token: NOT_NEEDED
                  base: ""
                  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                  plugin_steam: yes
                  plugin_steam_user: ${{ secrets.STEAM_USER }}
                  plugin_steam_sections: player
                  plugin_steam_playtime_threshold: 2

            - name: Recently played games
              uses: lowlighter/metrics@latest
              with:
                  filename: assets/metrics.plugin.steam.recent.svg
                  token: NOT_NEEDED
                  base: ""
                  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                  plugin_steam: yes
                  plugin_steam_user: ${{ secrets.STEAM_USER }}
                  plugin_steam_sections: recently-played
                  plugin_steam_recent_games_limit: 3
                  plugin_steam_achievements_limit: 1
