name: metrics

on:
    schedule: [{ cron: "0 16 * * *" }]
    workflow_dispatch:

jobs:
    metrics:
        runs-on: ubuntu-latest
        steps:
            - name: Full history calendar
              uses: lowlighter/metrics@latest
              with:
                  filename: assets/metrics.plugin.calendar.full.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: ""
                  plugin_calendar: yes
                  plugin_calendar_limit: 0

            - name: Steam
              uses: lowlighter/metrics@latest
              with:
                  filename: assets/metrics.plugin.steam.svg
                  token: NOT_NEEDED
                  base: ""
                  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
                  plugin_steam: yes
                  plugin_steam_user: ${{ secrets.STEAM_USER }}
                  plugin_steam_sections: player, recently-played
                  plugin_steam_playtime_threshold: 2
                  plugin_steam_recent_games_limit: 1
                  plugin_steam_achievements_limit: 0
