name: metrics.api.steam

on:
  schedule: [{ cron: "0 16 * * *" }]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Recently played games
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: ${{ secrets.STEAM_USER }}
          plugin_steam_sections: player, recently-played
          plugin_steam_recent_games_limit: 2
          plugin_steam_achievements_limit: 2
          plugin_steam_playtime_threshold: 2
